// Generates data/users.yaml with bcrypt-hashed passwords.
// Re-running this script overwrites users.yaml — use only for first-time seeding.
import fs from 'node:fs';
import path from 'node:path';
import bcrypt from 'bcryptjs';

const PASSWORD = 'ZSO1234';
const USERS = [
  { username: 'admin', role: 'admin' },
  { username: 'Of',    role: 'Offizier' },
  { username: 'Uof',   role: 'Unteroffizier' },
  { username: 'AdZS',  role: 'Soldat' },
];

const hash = bcrypt.hashSync(PASSWORD, 10);
let yaml = '# Auto-generated by scripts/seed-users.js. Edit by hand or run `npm run hash <pw>` for a new bcrypt hash.\nusers:\n';
for (const u of USERS) {
  yaml += `  ${u.username}:\n    role: ${u.role}\n    passwordHash: "${hash}"\n`;
}
const out = path.resolve('data/users.yaml');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, yaml);
console.log(`Wrote ${out} with ${USERS.length} users (password: ${PASSWORD}).`);
